# Generated by Django 5.1.6 on 2025-02-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_staff_wards'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wards',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='lname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='lastname',
        ),
    ]
