# Generated by Django 5.1.6 on 2025-02-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_delete_wards_rename_lname_staff_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bedsnumber', models.CharField(max_length=15)),
                ('availablebeds', models.CharField(max_length=15)),
            ],
        ),
    ]
