# Generated by Django 5.1.6 on 2025-02-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_wards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wards',
            new_name='Ward',
        ),
    ]
