# Generated by Django 5.1.6 on 2025-02-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_rename_wards_ward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ward',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='lastname',
        ),
    ]
