# Generated by Django 5.1.6 on 2025-02-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0007_delete_ward_rename_firstname_staff_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('beds', models.IntegerField()),
                ('bedsavailable', models.IntegerField()),
            ],
        ),
    ]
